services:
  - type: web
    name: 10-minute-mail
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
