// nativeName: how the language calls itself in its own script.
// This is always shown in the dropdown regardless of the active UI language,
// so a user can find and recognise their own language even when the UI is in another tongue.
export const USER_LANGUAGES = [
  { name: 'English',              code: 'en',    nativeName: 'English' },
  { name: 'Albanian',             code: 'sq',    nativeName: 'Shqip' },
  { name: 'Arabic',               code: 'ar',    nativeName: 'العربية' },
  { name: 'Bulgarian',            code: 'bg',    nativeName: 'Български' },
  { name: 'Catalan',              code: 'ca',    nativeName: 'Català' },
  { name: 'Chinese (Simplified)', code: 'zh-CN', nativeName: '中文（简体）' },
  { name: 'Croatian',             code: 'hr',    nativeName: 'Hrvatski' },
  { name: 'Czech',                code: 'cs',    nativeName: 'Čeština' },
  { name: 'Danish',               code: 'da',    nativeName: 'Dansk' },
  { name: 'Dutch',                code: 'nl',    nativeName: 'Nederlands' },
  { name: 'Esperanto',            code: 'eo',    nativeName: 'Esperanto' },
  { name: 'Estonian',             code: 'et',    nativeName: 'Eesti' },
  { name: 'Finnish',              code: 'fi',    nativeName: 'Suomi' },
  { name: 'French',               code: 'fr',    nativeName: 'Français' },
  { name: 'Galician',             code: 'gl',    nativeName: 'Galego' },
  { name: 'German',               code: 'de',    nativeName: 'Deutsch' },
  { name: 'Greek',                code: 'el',    nativeName: 'Ελληνικά' },
  { name: 'Hebrew',               code: 'he',    nativeName: 'עברית' },
  { name: 'Hungarian',            code: 'hu',    nativeName: 'Magyar' },
  { name: 'Indonesian',           code: 'id',    nativeName: 'Bahasa Indonesia' },
  { name: 'Italian',              code: 'it',    nativeName: 'Italiano' },
  { name: 'Japanese',             code: 'ja',    nativeName: '日本語' },
  { name: 'Korean',               code: 'ko',    nativeName: '한국어' },
  { name: 'Latvian',              code: 'lv',    nativeName: 'Latviešu' },
  { name: 'Lithuanian',           code: 'lt',    nativeName: 'Lietuvių' },
  { name: 'Norwegian',            code: 'no',    nativeName: 'Norsk' },
  { name: 'Persian',              code: 'fa',    nativeName: 'فارسی' },
  { name: 'Polish',               code: 'pl',    nativeName: 'Polski' },
  { name: 'Portuguese',           code: 'pt',    nativeName: 'Português' },
  { name: 'Romanian',             code: 'ro',    nativeName: 'Română' },
  { name: 'Russian',              code: 'ru',    nativeName: 'Русский' },
  { name: 'Serbian',              code: 'sr',    nativeName: 'Српски' },
  { name: 'Slovak',               code: 'sk',    nativeName: 'Slovenčina' },
  { name: 'Slovenian',            code: 'sl',    nativeName: 'Slovenščina' },
  { name: 'Spanish',              code: 'es',    nativeName: 'Español' },
  { name: 'Swedish',              code: 'sv',    nativeName: 'Svenska' },
  { name: 'Thai',                 code: 'th',    nativeName: 'ไทย' },
  { name: 'Turkish',              code: 'tr',    nativeName: 'Türkçe' },
  { name: 'Ukrainian',            code: 'uk',    nativeName: 'Українська' },
  { name: 'Vietnamese',           code: 'vi',    nativeName: 'Tiếng Việt' },
];

export const ALL_LANGUAGES = USER_LANGUAGES;
