/**
 * languageNames[uiLocale][langCode] = "Name of langCode in uiLocale"
 *
 * This lets the language dropdown show every language's name translated
 * into whichever language the UI is currently set to.
 * e.g. when currentLanguage === 'ar', the dropdown shows "الإنجليزية" for en,
 * "الفرنسية" for fr, etc.
 */
export const languageNames = {
  en: {
    en: 'English', sq: 'Albanian', ar: 'Arabic', bg: 'Bulgarian',
    ca: 'Catalan', 'zh-CN': 'Chinese (Simplified)', hr: 'Croatian',
    cs: 'Czech', da: 'Danish', nl: 'Dutch', eo: 'Esperanto',
    et: 'Estonian', fi: 'Finnish', fr: 'French', gl: 'Galician',
    de: 'German', el: 'Greek', he: 'Hebrew', hu: 'Hungarian',
    id: 'Indonesian', it: 'Italian', ja: 'Japanese', ko: 'Korean',
    lv: 'Latvian', lt: 'Lithuanian', no: 'Norwegian', fa: 'Persian',
    pl: 'Polish', pt: 'Portuguese', ro: 'Romanian', ru: 'Russian',
    sr: 'Serbian', sk: 'Slovak', sl: 'Slovenian', es: 'Spanish',
    sv: 'Swedish', th: 'Thai', tr: 'Turkish', uk: 'Ukrainian', vi: 'Vietnamese',
  },
  sq: {
    en: 'Anglisht', sq: 'Shqip', ar: 'Arabisht', bg: 'Bullgarisht',
    ca: 'Katalonisht', 'zh-CN': 'Kinezisht (e thjeshtësuar)', hr: 'Kroatisht',
    cs: 'Çekisht', da: 'Danisht', nl: 'Hollandisht', eo: 'Esperanto',
    et: 'Estonisht', fi: 'Finlandisht', fr: 'Frëngjisht', gl: 'Galisianisht',
    de: 'Gjermanisht', el: 'Greqisht', he: 'Hebraisht', hu: 'Hungarisht',
    id: 'Indonezisht', it: 'Italisht', ja: 'Japonisht', ko: 'Koreanisht',
    lv: 'Letonisht', lt: 'Lituanisht', no: 'Norvegjisht', fa: 'Persisht',
    pl: 'Polonisht', pt: 'Portugalisht', ro: 'Rumanisht', ru: 'Rusisht',
    sr: 'Serbisht', sk: 'Sllovakisht', sl: 'Sllovenisht', es: 'Spanjisht',
    sv: 'Suedisht', th: 'Tajlandisht', tr: 'Turqisht', uk: 'Ukrainisht', vi: 'Vietnamisht',
  },
  ar: {
    en: 'الإنجليزية', sq: 'الألبانية', ar: 'العربية', bg: 'البلغارية',
    ca: 'الكتالانية', 'zh-CN': 'الصينية المبسطة', hr: 'الكرواتية',
    cs: 'التشيكية', da: 'الدنماركية', nl: 'الهولندية', eo: 'الإسبرانتو',
    et: 'الإستونية', fi: 'الفنلندية', fr: 'الفرنسية', gl: 'الغاليسية',
    de: 'الألمانية', el: 'اليونانية', he: 'العبرية', hu: 'المجرية',
    id: 'الإندونيسية', it: 'الإيطالية', ja: 'اليابانية', ko: 'الكورية',
    lv: 'اللاتفية', lt: 'الليتوانية', no: 'النرويجية', fa: 'الفارسية',
    pl: 'البولندية', pt: 'البرتغالية', ro: 'الرومانية', ru: 'الروسية',
    sr: 'الصربية', sk: 'السلوفاكية', sl: 'السلوفينية', es: 'الإسبانية',
    sv: 'السويدية', th: 'التايلاندية', tr: 'التركية', uk: 'الأوكرانية', vi: 'الفيتنامية',
  },
  bg: {
    en: 'Английски', sq: 'Албански', ar: 'Арабски', bg: 'Български',
    ca: 'Каталонски', 'zh-CN': 'Китайски (опростен)', hr: 'Хърватски',
    cs: 'Чешки', da: 'Датски', nl: 'Нидерландски', eo: 'Есперанто',
    et: 'Естонски', fi: 'Фински', fr: 'Френски', gl: 'Галисийски',
    de: 'Немски', el: 'Гръцки', he: 'Иврит', hu: 'Унгарски',
    id: 'Индонезийски', it: 'Италиански', ja: 'Японски', ko: 'Корейски',
    lv: 'Латвийски', lt: 'Литовски', no: 'Норвежки', fa: 'Персийски',
    pl: 'Полски', pt: 'Португалски', ro: 'Румънски', ru: 'Руски',
    sr: 'Сръбски', sk: 'Словашки', sl: 'Словенски', es: 'Испански',
    sv: 'Шведски', th: 'Тайски', tr: 'Турски', uk: 'Украински', vi: 'Виетнамски',
  },
  ca: {
    en: 'Anglès', sq: 'Albanès', ar: 'Àrab', bg: 'Búlgar',
    ca: 'Català', 'zh-CN': 'Xinès (simplificat)', hr: 'Croat',
    cs: 'Txec', da: 'Danès', nl: 'Neerlandès', eo: 'Esperanto',
    et: 'Estonià', fi: 'Finlandès', fr: 'Francès', gl: 'Gallec',
    de: 'Alemany', el: 'Grec', he: 'Hebreu', hu: 'Hongarès',
    id: 'Indonesi', it: 'Italià', ja: 'Japonès', ko: 'Coreà',
    lv: 'Letó', lt: 'Lituà', no: 'Noruec', fa: 'Persa',
    pl: 'Polonès', pt: 'Portuguès', ro: 'Romanès', ru: 'Rus',
    sr: 'Serbi', sk: 'Eslovac', sl: 'Eslovè', es: 'Espanyol',
    sv: 'Suec', th: 'Tailandès', tr: 'Turc', uk: 'Ucraïnès', vi: 'Vietnamita',
  },
  'zh-CN': {
    en: '英语', sq: '阿尔巴尼亚语', ar: '阿拉伯语', bg: '保加利亚语',
    ca: '加泰罗尼亚语', 'zh-CN': '中文（简体）', hr: '克罗地亚语',
    cs: '捷克语', da: '丹麦语', nl: '荷兰语', eo: '世界语',
    et: '爱沙尼亚语', fi: '芬兰语', fr: '法语', gl: '加利西亚语',
    de: '德语', el: '希腊语', he: '希伯来语', hu: '匈牙利语',
    id: '印度尼西亚语', it: '意大利语', ja: '日语', ko: '韩语',
    lv: '拉脱维亚语', lt: '立陶宛语', no: '挪威语', fa: '波斯语',
    pl: '波兰语', pt: '葡萄牙语', ro: '罗马尼亚语', ru: '俄语',
    sr: '塞尔维亚语', sk: '斯洛伐克语', sl: '斯洛文尼亚语', es: '西班牙语',
    sv: '瑞典语', th: '泰语', tr: '土耳其语', uk: '乌克兰语', vi: '越南语',
  },
  hr: {
    en: 'Engleski', sq: 'Albanski', ar: 'Arapski', bg: 'Bugarski',
    ca: 'Katalonski', 'zh-CN': 'Kineski (pojednostavljen)', hr: 'Hrvatski',
    cs: 'Češki', da: 'Danski', nl: 'Nizozemski', eo: 'Esperanto',
    et: 'Estonski', fi: 'Finski', fr: 'Francuski', gl: 'Galicijski',
    de: 'Njemački', el: 'Grčki', he: 'Hebrejski', hu: 'Mađarski',
    id: 'Indonezijski', it: 'Talijanski', ja: 'Japanski', ko: 'Korejski',
    lv: 'Latvijski', lt: 'Litvanski', no: 'Norveški', fa: 'Perzijski',
    pl: 'Poljski', pt: 'Portugalski', ro: 'Rumunjski', ru: 'Ruski',
    sr: 'Srpski', sk: 'Slovački', sl: 'Slovenski', es: 'Španjolski',
    sv: 'Švedski', th: 'Tajlandski', tr: 'Turski', uk: 'Ukrajinski', vi: 'Vijetnamski',
  },
  cs: {
    en: 'Angličtina', sq: 'Albánština', ar: 'Arabština', bg: 'Bulharština',
    ca: 'Katalánština', 'zh-CN': 'Čínština (zjednodušená)', hr: 'Chorvatština',
    cs: 'Čeština', da: 'Dánština', nl: 'Nizozemština', eo: 'Esperanto',
    et: 'Estonština', fi: 'Finština', fr: 'Francouzština', gl: 'Galicijština',
    de: 'Němčina', el: 'Řečtina', he: 'Hebrejština', hu: 'Maďarština',
    id: 'Indonéština', it: 'Italština', ja: 'Japonština', ko: 'Korejština',
    lv: 'Lotyšština', lt: 'Litevština', no: 'Norština', fa: 'Perština',
    pl: 'Polština', pt: 'Portugalština', ro: 'Rumunština', ru: 'Ruština',
    sr: 'Srbština', sk: 'Slovenština', sl: 'Slovinština', es: 'Španělština',
    sv: 'Švédština', th: 'Thajština', tr: 'Turečtina', uk: 'Ukrajinština', vi: 'Vietnamština',
  },
  da: {
    en: 'Engelsk', sq: 'Albansk', ar: 'Arabisk', bg: 'Bulgarsk',
    ca: 'Catalansk', 'zh-CN': 'Kinesisk (forenklet)', hr: 'Kroatisk',
    cs: 'Tjekkisk', da: 'Dansk', nl: 'Hollandsk', eo: 'Esperanto',
    et: 'Estisk', fi: 'Finsk', fr: 'Fransk', gl: 'Galicisk',
    de: 'Tysk', el: 'Græsk', he: 'Hebraisk', hu: 'Ungarsk',
    id: 'Indonesisk', it: 'Italiensk', ja: 'Japansk', ko: 'Koreansk',
    lv: 'Lettisk', lt: 'Litauisk', no: 'Norsk', fa: 'Persisk',
    pl: 'Polsk', pt: 'Portugisisk', ro: 'Rumænsk', ru: 'Russisk',
    sr: 'Serbisk', sk: 'Slovakisk', sl: 'Slovensk', es: 'Spansk',
    sv: 'Svensk', th: 'Thai', tr: 'Tyrkisk', uk: 'Ukrainsk', vi: 'Vietnamesisk',
  },
  nl: {
    en: 'Engels', sq: 'Albanees', ar: 'Arabisch', bg: 'Bulgaars',
    ca: 'Catalaans', 'zh-CN': 'Chinees (vereenvoudigd)', hr: 'Kroatisch',
    cs: 'Tsjechisch', da: 'Deens', nl: 'Nederlands', eo: 'Esperanto',
    et: 'Ests', fi: 'Fins', fr: 'Frans', gl: 'Galicisch',
    de: 'Duits', el: 'Grieks', he: 'Hebreeuws', hu: 'Hongaars',
    id: 'Indonesisch', it: 'Italiaans', ja: 'Japans', ko: 'Koreaans',
    lv: 'Lets', lt: 'Litouws', no: 'Noors', fa: 'Perzisch',
    pl: 'Pools', pt: 'Portugees', ro: 'Roemeens', ru: 'Russisch',
    sr: 'Servisch', sk: 'Slowaaks', sl: 'Sloveens', es: 'Spaans',
    sv: 'Zweeds', th: 'Thais', tr: 'Turks', uk: 'Oekraïens', vi: 'Vietnamees',
  },
  eo: {
    en: 'Angla', sq: 'Albana', ar: 'Araba', bg: 'Bulgara',
    ca: 'Kataluna', 'zh-CN': 'Ĉina (simpligita)', hr: 'Kroata',
    cs: 'Ĉeĥa', da: 'Dana', nl: 'Nederlanda', eo: 'Esperanto',
    et: 'Estona', fi: 'Finna', fr: 'Franca', gl: 'Galega',
    de: 'Germana', el: 'Greka', he: 'Hebrea', hu: 'Hungara',
    id: 'Indonezia', it: 'Itala', ja: 'Japana', ko: 'Korea',
    lv: 'Latva', lt: 'Litova', no: 'Norvega', fa: 'Persa',
    pl: 'Pola', pt: 'Portugala', ro: 'Rumana', ru: 'Rusa',
    sr: 'Serba', sk: 'Slovaka', sl: 'Slovena', es: 'Hispana',
    sv: 'Sveda', th: 'Taja', tr: 'Turka', uk: 'Ukraina', vi: 'Vjetnama',
  },
  et: {
    en: 'Inglise', sq: 'Albaania', ar: 'Araabia', bg: 'Bulgaaria',
    ca: 'Katalaani', 'zh-CN': 'Hiina (lihtsustatud)', hr: 'Horvaadi',
    cs: 'Tšehhi', da: 'Taani', nl: 'Hollandi', eo: 'Esperanto',
    et: 'Eesti', fi: 'Soome', fr: 'Prantsuse', gl: 'Galiitsia',
    de: 'Saksa', el: 'Kreeka', he: 'Heebrea', hu: 'Ungari',
    id: 'Indoneesia', it: 'Itaalia', ja: 'Jaapani', ko: 'Korea',
    lv: 'Läti', lt: 'Leedu', no: 'Norra', fa: 'Pärsia',
    pl: 'Poola', pt: 'Portugali', ro: 'Rumeenia', ru: 'Vene',
    sr: 'Serbia', sk: 'Slovaki', sl: 'Sloveeni', es: 'Hispaania',
    sv: 'Rootsi', th: 'Tai', tr: 'Türgi', uk: 'Ukraina', vi: 'Vietnami',
  },
  fi: {
    en: 'Englanti', sq: 'Albania', ar: 'Arabia', bg: 'Bulgaria',
    ca: 'Katalaani', 'zh-CN': 'Kiina (yksinkertaistettu)', hr: 'Kroatia',
    cs: 'Tšekki', da: 'Tanska', nl: 'Hollanti', eo: 'Esperanto',
    et: 'Viro', fi: 'Suomi', fr: 'Ranska', gl: 'Galiscia',
    de: 'Saksa', el: 'Kreikka', he: 'Heprea', hu: 'Unkari',
    id: 'Indonesia', it: 'Italia', ja: 'Japani', ko: 'Korea',
    lv: 'Latvia', lt: 'Liettua', no: 'Norja', fa: 'Persia',
    pl: 'Puola', pt: 'Portugali', ro: 'Romania', ru: 'Venäjä',
    sr: 'Serbia', sk: 'Slovakia', sl: 'Slovenia', es: 'Espanja',
    sv: 'Ruotsi', th: 'Thai', tr: 'Turkki', uk: 'Ukraina', vi: 'Vietnam',
  },
  fr: {
    en: 'Anglais', sq: 'Albanais', ar: 'Arabe', bg: 'Bulgare',
    ca: 'Catalan', 'zh-CN': 'Chinois simplifié', hr: 'Croate',
    cs: 'Tchèque', da: 'Danois', nl: 'Néerlandais', eo: 'Espéranto',
    et: 'Estonien', fi: 'Finnois', fr: 'Français', gl: 'Galicien',
    de: 'Allemand', el: 'Grec', he: 'Hébreu', hu: 'Hongrois',
    id: 'Indonésien', it: 'Italien', ja: 'Japonais', ko: 'Coréen',
    lv: 'Letton', lt: 'Lituanien', no: 'Norvégien', fa: 'Persan',
    pl: 'Polonais', pt: 'Portugais', ro: 'Roumain', ru: 'Russe',
    sr: 'Serbe', sk: 'Slovaque', sl: 'Slovène', es: 'Espagnol',
    sv: 'Suédois', th: 'Thaï', tr: 'Turc', uk: 'Ukrainien', vi: 'Vietnamien',
  },
  gl: {
    en: 'Inglés', sq: 'Albanés', ar: 'Árabe', bg: 'Búlgaro',
    ca: 'Catalán', 'zh-CN': 'Chinés simplificado', hr: 'Croata',
    cs: 'Checo', da: 'Dinamarqués', nl: 'Neerlandés', eo: 'Esperanto',
    et: 'Estoniano', fi: 'Finlandés', fr: 'Francés', gl: 'Galego',
    de: 'Alemán', el: 'Grego', he: 'Hebreo', hu: 'Húngaro',
    id: 'Indonesio', it: 'Italiano', ja: 'Xaponés', ko: 'Coreano',
    lv: 'Letón', lt: 'Lituano', no: 'Noruegués', fa: 'Persa',
    pl: 'Polaco', pt: 'Portugués', ro: 'Romanés', ru: 'Ruso',
    sr: 'Serbio', sk: 'Eslovaco', sl: 'Esloveno', es: 'Español',
    sv: 'Sueco', th: 'Tailandés', tr: 'Turco', uk: 'Ucraíno', vi: 'Vietnamita',
  },
  de: {
    en: 'Englisch', sq: 'Albanisch', ar: 'Arabisch', bg: 'Bulgarisch',
    ca: 'Katalanisch', 'zh-CN': 'Chinesisch (Vereinfacht)', hr: 'Kroatisch',
    cs: 'Tschechisch', da: 'Dänisch', nl: 'Niederländisch', eo: 'Esperanto',
    et: 'Estnisch', fi: 'Finnisch', fr: 'Französisch', gl: 'Galizisch',
    de: 'Deutsch', el: 'Griechisch', he: 'Hebräisch', hu: 'Ungarisch',
    id: 'Indonesisch', it: 'Italienisch', ja: 'Japanisch', ko: 'Koreanisch',
    lv: 'Lettisch', lt: 'Litauisch', no: 'Norwegisch', fa: 'Persisch',
    pl: 'Polnisch', pt: 'Portugiesisch', ro: 'Rumänisch', ru: 'Russisch',
    sr: 'Serbisch', sk: 'Slowakisch', sl: 'Slowenisch', es: 'Spanisch',
    sv: 'Schwedisch', th: 'Thailändisch', tr: 'Türkisch', uk: 'Ukrainisch', vi: 'Vietnamesisch',
  },
  el: {
    en: 'Αγγλικά', sq: 'Αλβανικά', ar: 'Αραβικά', bg: 'Βουλγαρικά',
    ca: 'Καταλανικά', 'zh-CN': 'Κινεζικά (Απλοποιημένα)', hr: 'Κροατικά',
    cs: 'Τσεχικά', da: 'Δανικά', nl: 'Ολλανδικά', eo: 'Εσπεράντο',
    et: 'Εσθονικά', fi: 'Φινλανδικά', fr: 'Γαλλικά', gl: 'Γαλικιανά',
    de: 'Γερμανικά', el: 'Ελληνικά', he: 'Εβραϊκά', hu: 'Ουγγρικά',
    id: 'Ινδονησιακά', it: 'Ιταλικά', ja: 'Ιαπωνικά', ko: 'Κορεατικά',
    lv: 'Λετονικά', lt: 'Λιθουανικά', no: 'Νορβηγικά', fa: 'Περσικά',
    pl: 'Πολωνικά', pt: 'Πορτογαλικά', ro: 'Ρουμανικά', ru: 'Ρωσικά',
    sr: 'Σερβικά', sk: 'Σλοβακικά', sl: 'Σλοβενικά', es: 'Ισπανικά',
    sv: 'Σουηδικά', th: 'Ταϊλανδικά', tr: 'Τουρκικά', uk: 'Ουκρανικά', vi: 'Βιετναμικά',
  },
  he: {
    en: 'אנגלית', sq: 'אלבנית', ar: 'ערבית', bg: 'בולגרית',
    ca: 'קטלנית', 'zh-CN': 'סינית (פשוטה)', hr: 'קרואטית',
    cs: "צ'כית", da: 'דנית', nl: 'הולנדית', eo: 'אספרנטו',
    et: 'אסטונית', fi: 'פינית', fr: 'צרפתית', gl: 'גליסית',
    de: 'גרמנית', el: 'יוונית', he: 'עברית', hu: 'הונגרית',
    id: 'אינדונזית', it: 'איטלקית', ja: 'יפנית', ko: 'קורנית',
    lv: 'לטבית', lt: 'ליטאית', no: 'נורווגית', fa: 'פרסית',
    pl: 'פולנית', pt: 'פורטוגלית', ro: 'רומנית', ru: 'רוסית',
    sr: 'סרבית', sk: 'סלובקית', sl: 'סלובנית', es: 'ספרדית',
    sv: 'שוודית', th: 'תאית', tr: 'טורקית', uk: 'אוקראינית', vi: 'וייטנאמית',
  },
  hu: {
    en: 'Angol', sq: 'Albán', ar: 'Arab', bg: 'Bolgár',
    ca: 'Katalán', 'zh-CN': 'Kínai (egyszerűsített)', hr: 'Horvát',
    cs: 'Cseh', da: 'Dán', nl: 'Holland', eo: 'Eszperantó',
    et: 'Észt', fi: 'Finn', fr: 'Francia', gl: 'Galiciai',
    de: 'Német', el: 'Görög', he: 'Héber', hu: 'Magyar',
    id: 'Indonéz', it: 'Olasz', ja: 'Japán', ko: 'Koreai',
    lv: 'Lett', lt: 'Litván', no: 'Norvég', fa: 'Perzsa',
    pl: 'Lengyel', pt: 'Portugál', ro: 'Román', ru: 'Orosz',
    sr: 'Szerb', sk: 'Szlovák', sl: 'Szlovén', es: 'Spanyol',
    sv: 'Svéd', th: 'Thai', tr: 'Török', uk: 'Ukrán', vi: 'Vietnami',
  },
  id: {
    en: 'Inggris', sq: 'Albania', ar: 'Arab', bg: 'Bulgaria',
    ca: 'Katalan', 'zh-CN': 'Tionghoa Sederhana', hr: 'Kroasia',
    cs: 'Ceska', da: 'Denmark', nl: 'Belanda', eo: 'Esperanto',
    et: 'Estonia', fi: 'Finlandia', fr: 'Perancis', gl: 'Galisia',
    de: 'Jerman', el: 'Yunani', he: 'Ibrani', hu: 'Hungaria',
    id: 'Indonesia', it: 'Italia', ja: 'Jepang', ko: 'Korea',
    lv: 'Latvia', lt: 'Lituania', no: 'Norwegia', fa: 'Persia',
    pl: 'Polandia', pt: 'Portugis', ro: 'Rumania', ru: 'Rusia',
    sr: 'Serbia', sk: 'Slowakia', sl: 'Slovenia', es: 'Spanyol',
    sv: 'Swedia', th: 'Thailand', tr: 'Turki', uk: 'Ukraina', vi: 'Vietnam',
  },
  it: {
    en: 'Inglese', sq: 'Albanese', ar: 'Arabo', bg: 'Bulgaro',
    ca: 'Catalano', 'zh-CN': 'Cinese semplificato', hr: 'Croato',
    cs: 'Ceco', da: 'Danese', nl: 'Olandese', eo: 'Esperanto',
    et: 'Estone', fi: 'Finlandese', fr: 'Francese', gl: 'Galiziano',
    de: 'Tedesco', el: 'Greco', he: 'Ebraico', hu: 'Ungherese',
    id: 'Indonesiano', it: 'Italiano', ja: 'Giapponese', ko: 'Coreano',
    lv: 'Lettone', lt: 'Lituano', no: 'Norvegese', fa: 'Persiano',
    pl: 'Polacco', pt: 'Portoghese', ro: 'Rumeno', ru: 'Russo',
    sr: 'Serbo', sk: 'Slovacco', sl: 'Sloveno', es: 'Spagnolo',
    sv: 'Svedese', th: 'Tailandese', tr: 'Turco', uk: 'Ucraino', vi: 'Vietnamita',
  },
  ja: {
    en: '英語', sq: 'アルバニア語', ar: 'アラビア語', bg: 'ブルガリア語',
    ca: 'カタロニア語', 'zh-CN': '中国語（簡体字）', hr: 'クロアチア語',
    cs: 'チェコ語', da: 'デンマーク語', nl: 'オランダ語', eo: 'エスペラント語',
    et: 'エストニア語', fi: 'フィンランド語', fr: 'フランス語', gl: 'ガリシア語',
    de: 'ドイツ語', el: 'ギリシャ語', he: 'ヘブライ語', hu: 'ハンガリー語',
    id: 'インドネシア語', it: 'イタリア語', ja: '日本語', ko: '韓国語',
    lv: 'ラトビア語', lt: 'リトアニア語', no: 'ノルウェー語', fa: 'ペルシャ語',
    pl: 'ポーランド語', pt: 'ポルトガル語', ro: 'ルーマニア語', ru: 'ロシア語',
    sr: 'セルビア語', sk: 'スロバキア語', sl: 'スロベニア語', es: 'スペイン語',
    sv: 'スウェーデン語', th: 'タイ語', tr: 'トルコ語', uk: 'ウクライナ語', vi: 'ベトナム語',
  },
  ko: {
    en: '영어', sq: '알바니아어', ar: '아랍어', bg: '불가리아어',
    ca: '카탈로니아어', 'zh-CN': '중국어(간체)', hr: '크로아티아어',
    cs: '체코어', da: '덴마크어', nl: '네덜란드어', eo: '에스페란토',
    et: '에스토니아어', fi: '핀란드어', fr: '프랑스어', gl: '갈리시아어',
    de: '독일어', el: '그리스어', he: '히브리어', hu: '헝가리어',
    id: '인도네시아어', it: '이탈리아어', ja: '일본어', ko: '한국어',
    lv: '라트비아어', lt: '리투아니아어', no: '노르웨이어', fa: '페르시아어',
    pl: '폴란드어', pt: '포르투갈어', ro: '루마니아어', ru: '러시아어',
    sr: '세르비아어', sk: '슬로바키아어', sl: '슬로베니아어', es: '스페인어',
    sv: '스웨덴어', th: '태국어', tr: '터키어', uk: '우크라이나어', vi: '베트남어',
  },
  lv: {
    en: 'Angļu', sq: 'Albāņu', ar: 'Arābu', bg: 'Bulgāru',
    ca: 'Katalāņu', 'zh-CN': 'Ķīniešu (vienkāršotā)', hr: 'Horvātu',
    cs: 'Čehu', da: 'Dāņu', nl: 'Nīderlandiešu', eo: 'Esperanto',
    et: 'Igauņu', fi: 'Somu', fr: 'Franču', gl: 'Galisiešu',
    de: 'Vācu', el: 'Grieķu', he: 'Ivrits', hu: 'Ungāru',
    id: 'Indonēziešu', it: 'Itāliešu', ja: 'Japāņu', ko: 'Korejiešu',
    lv: 'Latviešu', lt: 'Lietuviešu', no: 'Norvēģu', fa: 'Persiešu',
    pl: 'Poļu', pt: 'Portugāļu', ro: 'Rumāņu', ru: 'Krievu',
    sr: 'Serbu', sk: 'Slovāku', sl: 'Slovēņu', es: 'Spāņu',
    sv: 'Zviedru', th: 'Taju', tr: 'Turku', uk: 'Ukraiņu', vi: 'Vjetnamiešu',
  },
  lt: {
    en: 'Anglų', sq: 'Albanų', ar: 'Arabų', bg: 'Bulgarų',
    ca: 'Katalonų', 'zh-CN': 'Kinų (supaprastinta)', hr: 'Kroatų',
    cs: 'Čekų', da: 'Danų', nl: 'Nyderlandų', eo: 'Esperanto',
    et: 'Estų', fi: 'Suomių', fr: 'Prancūzų', gl: 'Galisų',
    de: 'Vokiečių', el: 'Graikų', he: 'Hebrajų', hu: 'Vengrų',
    id: 'Indoneziečių', it: 'Italų', ja: 'Japonų', ko: 'Korėjiečių',
    lv: 'Latvių', lt: 'Lietuvių', no: 'Norvegų', fa: 'Persų',
    pl: 'Lenkų', pt: 'Portugalų', ro: 'Rumunų', ru: 'Rusų',
    sr: 'Serbų', sk: 'Slovakų', sl: 'Slovėnų', es: 'Ispanų',
    sv: 'Švedų', th: 'Tajų', tr: 'Turkų', uk: 'Ukrainiečių', vi: 'Vietnamiečių',
  },
  no: {
    en: 'Engelsk', sq: 'Albansk', ar: 'Arabisk', bg: 'Bulgarsk',
    ca: 'Katalansk', 'zh-CN': 'Kinesisk (forenklet)', hr: 'Kroatisk',
    cs: 'Tsjekkisk', da: 'Dansk', nl: 'Nederlandsk', eo: 'Esperanto',
    et: 'Estisk', fi: 'Finsk', fr: 'Fransk', gl: 'Galisisk',
    de: 'Tysk', el: 'Gresk', he: 'Hebraisk', hu: 'Ungarsk',
    id: 'Indonesisk', it: 'Italiensk', ja: 'Japansk', ko: 'Koreansk',
    lv: 'Latvisk', lt: 'Litauisk', no: 'Norsk', fa: 'Persisk',
    pl: 'Polsk', pt: 'Portugisisk', ro: 'Rumensk', ru: 'Russisk',
    sr: 'Serbisk', sk: 'Slovakisk', sl: 'Slovensk', es: 'Spansk',
    sv: 'Svensk', th: 'Thai', tr: 'Tyrkisk', uk: 'Ukrainsk', vi: 'Vietnamesisk',
  },
  fa: {
    en: 'انگلیسی', sq: 'آلبانیایی', ar: 'عربی', bg: 'بلغاری',
    ca: 'کاتالان', 'zh-CN': 'چینی ساده‌شده', hr: 'کرواتی',
    cs: 'چکی', da: 'دانمارکی', nl: 'هلندی', eo: 'اسپرانتو',
    et: 'استونیایی', fi: 'فنلاندی', fr: 'فرانسوی', gl: 'گالیسی',
    de: 'آلمانی', el: 'یونانی', he: 'عبری', hu: 'مجاری',
    id: 'اندونزیایی', it: 'ایتالیایی', ja: 'ژاپنی', ko: 'کره‌ای',
    lv: 'لتونیایی', lt: 'لیتوانیایی', no: 'نروژی', fa: 'فارسی',
    pl: 'لهستانی', pt: 'پرتغالی', ro: 'رومانیایی', ru: 'روسی',
    sr: 'صربی', sk: 'اسلواکی', sl: 'اسلوونیایی', es: 'اسپانیایی',
    sv: 'سوئدی', th: 'تایلندی', tr: 'ترکی', uk: 'اوکراینی', vi: 'ویتنامی',
  },
  pl: {
    en: 'Angielski', sq: 'Albański', ar: 'Arabski', bg: 'Bułgarski',
    ca: 'Kataloński', 'zh-CN': 'Chiński uproszczony', hr: 'Chorwacki',
    cs: 'Czeski', da: 'Duński', nl: 'Holenderski', eo: 'Esperanto',
    et: 'Estoński', fi: 'Fiński', fr: 'Francuski', gl: 'Galicyjski',
    de: 'Niemiecki', el: 'Grecki', he: 'Hebrajski', hu: 'Węgierski',
    id: 'Indonezyjski', it: 'Włoski', ja: 'Japoński', ko: 'Koreański',
    lv: 'Łotewski', lt: 'Litewski', no: 'Norweski', fa: 'Perski',
    pl: 'Polski', pt: 'Portugalski', ro: 'Rumuński', ru: 'Rosyjski',
    sr: 'Serbski', sk: 'Słowacki', sl: 'Słoweński', es: 'Hiszpański',
    sv: 'Szwedzki', th: 'Tajski', tr: 'Turecki', uk: 'Ukraiński', vi: 'Wietnamski',
  },
  pt: {
    en: 'Inglês', sq: 'Albanês', ar: 'Árabe', bg: 'Búlgaro',
    ca: 'Catalão', 'zh-CN': 'Chinês simplificado', hr: 'Croata',
    cs: 'Tcheco', da: 'Dinamarquês', nl: 'Holandês', eo: 'Esperanto',
    et: 'Estoniano', fi: 'Finlandês', fr: 'Francês', gl: 'Galego',
    de: 'Alemão', el: 'Grego', he: 'Hebraico', hu: 'Húngaro',
    id: 'Indonésio', it: 'Italiano', ja: 'Japonês', ko: 'Coreano',
    lv: 'Letão', lt: 'Lituano', no: 'Norueguês', fa: 'Persa',
    pl: 'Polonês', pt: 'Português', ro: 'Romeno', ru: 'Russo',
    sr: 'Sérvio', sk: 'Eslovaco', sl: 'Esloveno', es: 'Espanhol',
    sv: 'Sueco', th: 'Tailandês', tr: 'Turco', uk: 'Ucraniano', vi: 'Vietnamita',
  },
  ro: {
    en: 'Engleză', sq: 'Albaneză', ar: 'Arabă', bg: 'Bulgară',
    ca: 'Catalană', 'zh-CN': 'Chineză simplificată', hr: 'Croată',
    cs: 'Cehă', da: 'Daneză', nl: 'Olandeză', eo: 'Esperanto',
    et: 'Estonă', fi: 'Finlandeză', fr: 'Franceză', gl: 'Galiciană',
    de: 'Germană', el: 'Greacă', he: 'Ebraică', hu: 'Maghiară',
    id: 'Indoneziană', it: 'Italiană', ja: 'Japoneză', ko: 'Coreeană',
    lv: 'Letonă', lt: 'Lituaniană', no: 'Norvegiană', fa: 'Persană',
    pl: 'Poloneză', pt: 'Portugheză', ro: 'Română', ru: 'Rusă',
    sr: 'Sârbă', sk: 'Slovacă', sl: 'Slovenă', es: 'Spaniolă',
    sv: 'Suedeză', th: 'Tailandeză', tr: 'Turcă', uk: 'Ucraineană', vi: 'Vietnameză',
  },
  ru: {
    en: 'Английский', sq: 'Албанский', ar: 'Арабский', bg: 'Болгарский',
    ca: 'Каталанский', 'zh-CN': 'Китайский (упрощённый)', hr: 'Хорватский',
    cs: 'Чешский', da: 'Датский', nl: 'Нидерландский', eo: 'Эсперанто',
    et: 'Эстонский', fi: 'Финский', fr: 'Французский', gl: 'Галисийский',
    de: 'Немецкий', el: 'Греческий', he: 'Иврит', hu: 'Венгерский',
    id: 'Индонезийский', it: 'Итальянский', ja: 'Японский', ko: 'Корейский',
    lv: 'Латышский', lt: 'Литовский', no: 'Норвежский', fa: 'Персидский',
    pl: 'Польский', pt: 'Португальский', ro: 'Румынский', ru: 'Русский',
    sr: 'Сербский', sk: 'Словацкий', sl: 'Словенский', es: 'Испанский',
    sv: 'Шведский', th: 'Тайский', tr: 'Турецкий', uk: 'Украинский', vi: 'Вьетнамский',
  },
  sr: {
    en: 'Енглески', sq: 'Албански', ar: 'Арапски', bg: 'Бугарски',
    ca: 'Каталонски', 'zh-CN': 'Кинески (поједностављени)', hr: 'Хрватски',
    cs: 'Чешки', da: 'Дански', nl: 'Холандски', eo: 'Есперанто',
    et: 'Естонски', fi: 'Фински', fr: 'Француски', gl: 'Галицијски',
    de: 'Немачки', el: 'Грчки', he: 'Хебрејски', hu: 'Мађарски',
    id: 'Индонежански', it: 'Италијански', ja: 'Јапански', ko: 'Корејски',
    lv: 'Летонски', lt: 'Литвански', no: 'Норвешки', fa: 'Персијски',
    pl: 'Пољски', pt: 'Португалски', ro: 'Румунски', ru: 'Руски',
    sr: 'Српски', sk: 'Словачки', sl: 'Словеначки', es: 'Шпански',
    sv: 'Шведски', th: 'Тајландски', tr: 'Турски', uk: 'Украјински', vi: 'Вијетнамски',
  },
  sk: {
    en: 'Angličtina', sq: 'Albánčina', ar: 'Arabčina', bg: 'Bulharčina',
    ca: 'Katalánčina', 'zh-CN': 'Čínština (zjednodušená)', hr: 'Chorvátčina',
    cs: 'Čeština', da: 'Dánčina', nl: 'Holandčina', eo: 'Esperanto',
    et: 'Estónčina', fi: 'Fínčina', fr: 'Francúzština', gl: 'Galícijčina',
    de: 'Nemčina', el: 'Gréčtina', he: 'Hebrejčina', hu: 'Maďarčina',
    id: 'Indonézština', it: 'Taliančina', ja: 'Japončina', ko: 'Kórejčina',
    lv: 'Lotyština', lt: 'Litovčina', no: 'Nórčina', fa: 'Perzština',
    pl: 'Poľština', pt: 'Portugalčina', ro: 'Rumunčina', ru: 'Ruština',
    sr: 'Srbčina', sk: 'Slovenčina', sl: 'Slovinčina', es: 'Španielčina',
    sv: 'Švédčina', th: 'Thajčina', tr: 'Turečtina', uk: 'Ukrajinčina', vi: 'Vietnamčina',
  },
  sl: {
    en: 'Angleščina', sq: 'Albanščina', ar: 'Arabščina', bg: 'Bolgarščina',
    ca: 'Katalonščina', 'zh-CN': 'Kitajščina (poenostavljena)', hr: 'Hrvaščina',
    cs: 'Češčina', da: 'Danščina', nl: 'Nizozemščina', eo: 'Esperanto',
    et: 'Estonščina', fi: 'Finščina', fr: 'Francoščina', gl: 'Galicijščina',
    de: 'Nemščina', el: 'Grščina', he: 'Hebrejščina', hu: 'Madžarščina',
    id: 'Indonezijščina', it: 'Italijanščina', ja: 'Japonščina', ko: 'Korejščina',
    lv: 'Latvijščina', lt: 'Litovščina', no: 'Norveščina', fa: 'Perzijščina',
    pl: 'Poljščina', pt: 'Portugalščina', ro: 'Romunščina', ru: 'Ruščina',
    sr: 'Srbščina', sk: 'Slovaščina', sl: 'Slovenščina', es: 'Španščina',
    sv: 'Švedščina', th: 'Tajščina', tr: 'Turščina', uk: 'Ukrajinščina', vi: 'Vietnamščina',
  },
  es: {
    en: 'Inglés', sq: 'Albanés', ar: 'Árabe', bg: 'Búlgaro',
    ca: 'Catalán', 'zh-CN': 'Chino simplificado', hr: 'Croata',
    cs: 'Checo', da: 'Danés', nl: 'Neerlandés', eo: 'Esperanto',
    et: 'Estonio', fi: 'Finlandés', fr: 'Francés', gl: 'Gallego',
    de: 'Alemán', el: 'Griego', he: 'Hebreo', hu: 'Húngaro',
    id: 'Indonesio', it: 'Italiano', ja: 'Japonés', ko: 'Coreano',
    lv: 'Letón', lt: 'Lituano', no: 'Noruego', fa: 'Persa',
    pl: 'Polaco', pt: 'Portugués', ro: 'Rumano', ru: 'Ruso',
    sr: 'Serbio', sk: 'Eslovaco', sl: 'Esloveno', es: 'Español',
    sv: 'Sueco', th: 'Tailandés', tr: 'Turco', uk: 'Ucraniano', vi: 'Vietnamita',
  },
  sv: {
    en: 'Engelska', sq: 'Albanska', ar: 'Arabiska', bg: 'Bulgariska',
    ca: 'Katalanska', 'zh-CN': 'Kinesiska (förenklad)', hr: 'Kroatiska',
    cs: 'Tjeckiska', da: 'Danska', nl: 'Nederländska', eo: 'Esperanto',
    et: 'Estniska', fi: 'Finska', fr: 'Franska', gl: 'Galiciska',
    de: 'Tyska', el: 'Grekiska', he: 'Hebreiska', hu: 'Ungerska',
    id: 'Indonesiska', it: 'Italienska', ja: 'Japanska', ko: 'Koreanska',
    lv: 'Lettiska', lt: 'Litauiska', no: 'Norska', fa: 'Persiska',
    pl: 'Polska', pt: 'Portugisiska', ro: 'Rumänska', ru: 'Ryska',
    sr: 'Serbiska', sk: 'Slovakiska', sl: 'Slovenska', es: 'Spanska',
    sv: 'Svenska', th: 'Thailändska', tr: 'Turkiska', uk: 'Ukrainska', vi: 'Vietnamesiska',
  },
  th: {
    en: 'อังกฤษ', sq: 'แอลเบเนีย', ar: 'อาหรับ', bg: 'บัลแกเรีย',
    ca: 'คาตาลัน', 'zh-CN': 'จีนกลางแบบง่าย', hr: 'โครเอเชีย',
    cs: 'เช็ก', da: 'เดนมาร์ก', nl: 'ดัตช์', eo: 'เอสเปรันโต',
    et: 'เอสโตเนีย', fi: 'ฟินแลนด์', fr: 'ฝรั่งเศส', gl: 'กาลิเซีย',
    de: 'เยอรมัน', el: 'กรีก', he: 'ฮีบรู', hu: 'ฮังการี',
    id: 'อินโดนีเซีย', it: 'อิตาลี', ja: 'ญี่ปุ่น', ko: 'เกาหลี',
    lv: 'ลัตเวีย', lt: 'ลิทัวเนีย', no: 'นอร์เวย์', fa: 'เปอร์เซีย',
    pl: 'โปแลนด์', pt: 'โปรตุเกส', ro: 'โรมาเนีย', ru: 'รัสเซีย',
    sr: 'เซอร์เบีย', sk: 'สโลวัก', sl: 'สโลวีเนีย', es: 'สเปน',
    sv: 'สวีเดน', th: 'ไทย', tr: 'ตุรกี', uk: 'ยูเครน', vi: 'เวียดนาม',
  },
  tr: {
    en: 'İngilizce', sq: 'Arnavutça', ar: 'Arapça', bg: 'Bulgarca',
    ca: 'Katalanca', 'zh-CN': 'Çince (Basitleştirilmiş)', hr: 'Hırvatça',
    cs: 'Çekçe', da: 'Danca', nl: 'Felemenkçe', eo: 'Esperanto',
    et: 'Estonca', fi: 'Fince', fr: 'Fransızca', gl: 'Galiçyaca',
    de: 'Almanca', el: 'Yunanca', he: 'İbranice', hu: 'Macarca',
    id: 'Endonezce', it: 'İtalyanca', ja: 'Japonca', ko: 'Korece',
    lv: 'Letonca', lt: 'Litvanca', no: 'Norveçce', fa: 'Farsça',
    pl: 'Lehçe', pt: 'Portekizce', ro: 'Rumence', ru: 'Rusça',
    sr: 'Sırpça', sk: 'Slovakça', sl: 'Slovence', es: 'İspanyolca',
    sv: 'İsveççe', th: 'Tayca', tr: 'Türkçe', uk: 'Ukraynaca', vi: 'Vietnamca',
  },
  uk: {
    en: 'Англійська', sq: 'Албанська', ar: 'Арабська', bg: 'Болгарська',
    ca: 'Каталонська', 'zh-CN': 'Китайська (спрощена)', hr: 'Хорватська',
    cs: 'Чеська', da: 'Данська', nl: 'Нідерландська', eo: 'Есперанто',
    et: 'Естонська', fi: 'Фінська', fr: 'Французька', gl: 'Галісійська',
    de: 'Німецька', el: 'Грецька', he: 'Іврит', hu: 'Угорська',
    id: 'Індонезійська', it: 'Італійська', ja: 'Японська', ko: 'Корейська',
    lv: 'Латвійська', lt: 'Литовська', no: 'Норвезька', fa: 'Перська',
    pl: 'Польська', pt: 'Португальська', ro: 'Румунська', ru: 'Російська',
    sr: 'Сербська', sk: 'Словацька', sl: 'Словенська', es: 'Іспанська',
    sv: 'Шведська', th: 'Тайська', tr: 'Турецька', uk: 'Українська', vi: "В'єтнамська",
  },
  vi: {
    en: 'Tiếng Anh', sq: 'Tiếng Albania', ar: 'Tiếng Ả Rập', bg: 'Tiếng Bulgaria',
    ca: 'Tiếng Catalan', 'zh-CN': 'Tiếng Trung (Giản thể)', hr: 'Tiếng Croatia',
    cs: 'Tiếng Séc', da: 'Tiếng Đan Mạch', nl: 'Tiếng Hà Lan', eo: 'Tiếng Esperanto',
    et: 'Tiếng Estonia', fi: 'Tiếng Phần Lan', fr: 'Tiếng Pháp', gl: 'Tiếng Galicia',
    de: 'Tiếng Đức', el: 'Tiếng Hy Lạp', he: 'Tiếng Hebrew', hu: 'Tiếng Hungary',
    id: 'Tiếng Indonesia', it: 'Tiếng Ý', ja: 'Tiếng Nhật', ko: 'Tiếng Hàn',
    lv: 'Tiếng Latvia', lt: 'Tiếng Litva', no: 'Tiếng Na Uy', fa: 'Tiếng Ba Tư',
    pl: 'Tiếng Ba Lan', pt: 'Tiếng Bồ Đào Nha', ro: 'Tiếng Romania', ru: 'Tiếng Nga',
    sr: 'Tiếng Serbia', sk: 'Tiếng Slovak', sl: 'Tiếng Slovenia', es: 'Tiếng Tây Ban Nha',
    sv: 'Tiếng Thụy Điển', th: 'Tiếng Thái', tr: 'Tiếng Thổ Nhĩ Kỳ', uk: 'Tiếng Ukraina', vi: 'Tiếng Việt',
  },
};
